### ISSUE TITLE
Edit Distribution modal disappears when highlighting

### ISSUE THREAD

**Issue by ZakGriffith** [scaffold-eth/OP-RetroPGF3-Discovery-Voting#69] opened 2023-09-18 21:05 UTC
If you use the cursor to highlight the text in the Edit Distribution modal, the entire thing disappears.  Clicking in and hitting backspace does not have the same effect.  Highlighting was the only way I could reproduce this bug.  This only occurs for me in Chrome.  It works as intended in Forefox.

![ModalDisappear](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/079dffe6-e3ec-4a0a-b962-5cd1b76efc38)

**Comment by ZakGriffith** [comment] 2023-09-18 21:05
Firefox*

**Comment by escottalexander** [comment] 2023-09-20 23:48
Will look into this one.

**Comment by escottalexander** [comment] 2023-09-21 01:15
This is a duplicate of #62. looks like @KcPele and @Chirag018 are working on it.

**Closed by escottalexander** 2023-09-21 01:15 UTC
